[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "dotnet FiltCar.Api.dll"
healthcheckPath = "/api/auth/me"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
